/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { FlexProps, IconProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type Web1920OverridesProps = {
    Web1920?: PrimitiveOverrideProps<ViewProps>;
    Title?: PrimitiveOverrideProps<FlexProps>;
    "YUJIN WANG"?: PrimitiveOverrideProps<TextProps>;
    "Frame 3315"?: PrimitiveOverrideProps<FlexProps>;
    "akar-icons:github-fill16"?: PrimitiveOverrideProps<ViewProps>;
    Vector17?: PrimitiveOverrideProps<IconProps>;
    "akar-icons:linkedin-fill18"?: PrimitiveOverrideProps<ViewProps>;
    Vector19?: PrimitiveOverrideProps<IconProps>;
    Body?: PrimitiveOverrideProps<FlexProps>;
    Text?: PrimitiveOverrideProps<TextProps>;
    Education112?: PrimitiveOverrideProps<FlexProps>;
    "Frame 175113"?: PrimitiveOverrideProps<FlexProps>;
    EDUCATION?: PrimitiveOverrideProps<TextProps>;
    "Frame 17"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 11"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 10"?: PrimitiveOverrideProps<FlexProps>;
    "Sep 2020 - Dec 2024/May 2025 (Expected)"?: PrimitiveOverrideProps<TextProps>;
    "University of Wisconsin - Madison"?: PrimitiveOverrideProps<TextProps>;
    "Bachelor of Science in Computer Science"?: PrimitiveOverrideProps<TextProps>;
    "Bachelor of Science in Economics"?: PrimitiveOverrideProps<TextProps>;
    "Frame 13"?: PrimitiveOverrideProps<FlexProps>;
    Experience?: PrimitiveOverrideProps<FlexProps>;
    "Frame 176127"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 175128"?: PrimitiveOverrideProps<FlexProps>;
    EXPERIENCE?: PrimitiveOverrideProps<TextProps>;
    "Frame 15"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 14"?: PrimitiveOverrideProps<FlexProps>;
    "May 2023 - Aug 2023 (Jersey City, NJ)"?: PrimitiveOverrideProps<TextProps>;
    "HireBeat Inc. Full Stack Developer Intern"?: PrimitiveOverrideProps<TextProps>;
    "Nov 2021 - Dec 2022 (Madison, WI, Remote)"?: PrimitiveOverrideProps<TextProps>;
    "Alibaba Inc. Data Analyst Intern"?: PrimitiveOverrideProps<TextProps>;
    Education136?: PrimitiveOverrideProps<FlexProps>;
    "Frame 175137"?: PrimitiveOverrideProps<FlexProps>;
    CONTACT?: PrimitiveOverrideProps<TextProps>;
    Contact?: PrimitiveOverrideProps<ViewProps>;
    "Frame 42"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 38"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 34"?: PrimitiveOverrideProps<ViewProps>;
    Email?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 1654"?: PrimitiveOverrideProps<ViewProps>;
    "add your contact here..."?: PrimitiveOverrideProps<TextProps>;
    "Frame 39"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 35"?: PrimitiveOverrideProps<FlexProps>;
    Name?: PrimitiveOverrideProps<TextProps>;
    "Frame 197"?: PrimitiveOverrideProps<FlexProps>;
    "Rectangle 1655"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 198"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 41"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 40"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 36"?: PrimitiveOverrideProps<ViewProps>;
    Message?: PrimitiveOverrideProps<TextProps>;
    "Message Box"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1656"?: PrimitiveOverrideProps<IconProps>;
    "add your message here..."?: PrimitiveOverrideProps<TextProps>;
    "Frame 37"?: PrimitiveOverrideProps<ViewProps>;
    Send?: PrimitiveOverrideProps<TextProps>;
    Footer?: PrimitiveOverrideProps<FlexProps>;
    "Vector 12"?: PrimitiveOverrideProps<IconProps>;
    "Frame 43"?: PrimitiveOverrideProps<FlexProps>;
    "2023 GOOD LUCK"?: PrimitiveOverrideProps<TextProps>;
    "Frame 33159"?: PrimitiveOverrideProps<FlexProps>;
    "akar-icons:github-fill160"?: PrimitiveOverrideProps<ViewProps>;
    Vector161?: PrimitiveOverrideProps<IconProps>;
    "akar-icons:linkedin-fill162"?: PrimitiveOverrideProps<ViewProps>;
    Vector163?: PrimitiveOverrideProps<IconProps>;
    Skills?: PrimitiveOverrideProps<FlexProps>;
    "Frame 176165"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 175166"?: PrimitiveOverrideProps<FlexProps>;
    SKILLS?: PrimitiveOverrideProps<TextProps>;
    "Group 158"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 178"?: PrimitiveOverrideProps<FlexProps>;
    "akar-icons:html-fill"?: PrimitiveOverrideProps<ViewProps>;
    Group171?: PrimitiveOverrideProps<ViewProps>;
    Group172?: PrimitiveOverrideProps<ViewProps>;
    Vector173?: PrimitiveOverrideProps<IconProps>;
    Vector174?: PrimitiveOverrideProps<IconProps>;
    HTML?: PrimitiveOverrideProps<TextProps>;
    "Frame 186"?: PrimitiveOverrideProps<FlexProps>;
    "bi:git"?: PrimitiveOverrideProps<ViewProps>;
    Vector178?: PrimitiveOverrideProps<IconProps>;
    "GIT/Github"?: PrimitiveOverrideProps<TextProps>;
    "Frame 194"?: PrimitiveOverrideProps<FlexProps>;
    "bxl:unity"?: PrimitiveOverrideProps<ViewProps>;
    Vector182?: PrimitiveOverrideProps<IconProps>;
    Unity?: PrimitiveOverrideProps<TextProps>;
    "Frame 195"?: PrimitiveOverrideProps<FlexProps>;
    "ant-design:android-filled"?: PrimitiveOverrideProps<ViewProps>;
    Vector186?: PrimitiveOverrideProps<IconProps>;
    Android?: PrimitiveOverrideProps<TextProps>;
    "Frame 196"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 184"?: PrimitiveOverrideProps<FlexProps>;
    "bxl:java"?: PrimitiveOverrideProps<ViewProps>;
    Vector191?: PrimitiveOverrideProps<IconProps>;
    Vector192?: PrimitiveOverrideProps<IconProps>;
    Vector193?: PrimitiveOverrideProps<IconProps>;
    Java?: PrimitiveOverrideProps<TextProps>;
    "Frame 187"?: PrimitiveOverrideProps<FlexProps>;
    "cib:atlassian"?: PrimitiveOverrideProps<ViewProps>;
    Vector197?: PrimitiveOverrideProps<IconProps>;
    "Atlassian/Bitbucket"?: PrimitiveOverrideProps<TextProps>;
    "Frame 188"?: PrimitiveOverrideProps<FlexProps>;
    "cib:docker"?: PrimitiveOverrideProps<ViewProps>;
    Vector1101?: PrimitiveOverrideProps<IconProps>;
    Docker?: PrimitiveOverrideProps<TextProps>;
    "Frame 189"?: PrimitiveOverrideProps<FlexProps>;
    "cib:postman"?: PrimitiveOverrideProps<ViewProps>;
    Vector1105?: PrimitiveOverrideProps<IconProps>;
    Postman?: PrimitiveOverrideProps<TextProps>;
    "Frame 190"?: PrimitiveOverrideProps<FlexProps>;
    "cib:mysql"?: PrimitiveOverrideProps<ViewProps>;
    Vector1109?: PrimitiveOverrideProps<IconProps>;
    MySQL?: PrimitiveOverrideProps<TextProps>;
    "Frame 191"?: PrimitiveOverrideProps<FlexProps>;
    "akar-icons:postgresql-fill"?: PrimitiveOverrideProps<ViewProps>;
    Vector1113?: PrimitiveOverrideProps<IconProps>;
    PostgreSQL?: PrimitiveOverrideProps<TextProps>;
    "Frame 192"?: PrimitiveOverrideProps<FlexProps>;
    "akar-icons:react-fill"?: PrimitiveOverrideProps<ViewProps>;
    Group1117?: PrimitiveOverrideProps<ViewProps>;
    Group1118?: PrimitiveOverrideProps<ViewProps>;
    Vector1119?: PrimitiveOverrideProps<IconProps>;
    Vector1120?: PrimitiveOverrideProps<IconProps>;
    ReactJS1121?: PrimitiveOverrideProps<TextProps>;
    "Frame 193"?: PrimitiveOverrideProps<FlexProps>;
    "akar-icons:graphql-fill1123"?: PrimitiveOverrideProps<ViewProps>;
    Group1124?: PrimitiveOverrideProps<ViewProps>;
    Group1125?: PrimitiveOverrideProps<ViewProps>;
    Vector1126?: PrimitiveOverrideProps<IconProps>;
    GraphQL?: PrimitiveOverrideProps<TextProps>;
    "Frame 179"?: PrimitiveOverrideProps<FlexProps>;
    "akar-icons:css-fill"?: PrimitiveOverrideProps<ViewProps>;
    Vector1130?: PrimitiveOverrideProps<IconProps>;
    Vector1131?: PrimitiveOverrideProps<IconProps>;
    CSS?: PrimitiveOverrideProps<TextProps>;
    "Frame 180"?: PrimitiveOverrideProps<FlexProps>;
    "cib:js"?: PrimitiveOverrideProps<ViewProps>;
    Vector1135?: PrimitiveOverrideProps<IconProps>;
    Javascript?: PrimitiveOverrideProps<TextProps>;
    "Frame 181"?: PrimitiveOverrideProps<FlexProps>;
    "akar-icons:graphql-fill1138"?: PrimitiveOverrideProps<ViewProps>;
    Group1139?: PrimitiveOverrideProps<ViewProps>;
    Group1140?: PrimitiveOverrideProps<ViewProps>;
    Vector1141?: PrimitiveOverrideProps<IconProps>;
    ReactJS1142?: PrimitiveOverrideProps<TextProps>;
    "Frame 182"?: PrimitiveOverrideProps<FlexProps>;
    "simple-icons:cplusplus"?: PrimitiveOverrideProps<ViewProps>;
    Vector1145?: PrimitiveOverrideProps<IconProps>;
    "C++"?: PrimitiveOverrideProps<TextProps>;
    "Frame 183"?: PrimitiveOverrideProps<FlexProps>;
    "mdi:language-csharp"?: PrimitiveOverrideProps<ViewProps>;
    Vector1149?: PrimitiveOverrideProps<IconProps>;
    CSharp?: PrimitiveOverrideProps<TextProps>;
    "Frame 185"?: PrimitiveOverrideProps<FlexProps>;
    "simple-icons:springboot"?: PrimitiveOverrideProps<ViewProps>;
    Vector1153?: PrimitiveOverrideProps<IconProps>;
    "Spring Boot"?: PrimitiveOverrideProps<TextProps>;
    "Nav-logo"?: PrimitiveOverrideProps<ViewProps>;
    "Vector 13"?: PrimitiveOverrideProps<IconProps>;
    "ion:logo-capacitor"?: PrimitiveOverrideProps<ViewProps>;
    "image 1 (Traced)"?: PrimitiveOverrideProps<IconProps>;
} & EscapeHatchProps;
export declare type Web1920Props = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: Web1920OverridesProps | undefined | null;
}>;
export default function Web1920(props: Web1920Props): React.ReactElement;
